### PR TITLE
does not contain valid JSON Parse error on line 19

### PR DESCRIPTION
**Pull request by mikoweb**

### CODE REVIEW

**Comment by piotr-cz** [comment]
Thanks, I wonder how I installed the package myself then :eyes:

**Comment by mikoweb** [comment]
Now works, when I put code below into the composer.json:

```
"require": {
    "piotr-cz/twig-extensions-joomla": "0.3"
}
```

I published version 0.3 in the fork with minor changes.
https://github.com/mikoweb/Twig-extensions-Joomla/blob/dev-fork/composer.json

**Comment by piotr-cz** [comment]
I see you removed the required dependencies, what is the reason?

To be honest, ATM I'm looking for more generic/ recognized solution such as gettext like [g11n](https://github.com/elkuku/g11n/) but Joomla-Framework/Text has still many some advantages.

**Comment by mikoweb** [comment]
Removed, because I am using Joomla Platform not Framework. I'll create system plugin implements Twig Templates. My mistake. I should leave "twig/twig".

https://github.com/mikoweb/Twig-extensions-Joomla/commit/2f555f135f29b6216e6f93179606a8fb52252d5e
https://github.com/mikoweb/Twig-extensions-Joomla/commit/d43bc4e0b346cf6b1824cb16cff1aeb0df323fcd

**Pull request merged**
